# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Chromatic

on:
    pull_request:
        # Opened, synchronize, or reopened are the default types
        # We added ready_for_review to trigger the workflow is passed from draft to ready_for_review
        types: ["opened", "synchronize", "reopened", "ready_for_review"]
        branches-ignore:
          - changeset-release/*

jobs:
    chromatic:
        if: github.event.pull_request.draft == false
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Commit
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0
            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version-file: ".nvmrc"
                  cache: "pnpm"

            - name: Cache pnpm store
              uses: actions/cache@v3
              with:
                  path: |
                    node_modules
                    ~/.pnpm-store
                  key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
                  restore-keys: |
                    ${{ runner.os }}-pnpm-

            - name: Install Dependencies
              run: |
                corepack enable
                pnpm install --frozen-lockfile

            - name: Build Packages
              run: pnpm run build

            - name: Publish to Chromatic
              uses: chromaui/action@v11.4.0
              with:
                  projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
                  buildScriptName: build-sb-chroma
