# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Chromatic

on:
    pull_request:
        # Opened, synchronize, or reopened are the default types
        # We added ready_for_review to trigger the workflow is passed from draft to ready_for_review
        types: ["opened", "synchronize", "reopened", "ready_for_review"]
        branches-ignore:
          - changeset-release/*

jobs:
    chromatic:
        if: github.event.pull_request.draft == false
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Commit
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0
            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version-file: ".nvmrc"
                  cache: "yarn"
            - name: Install Dependencies
              run: yarn install --frozen-lockfile
            - name: Build Packages
              run: yarn build
            - name: Publish to Chromatic
              uses: chromaui/action@v1
              id: chromatic
              with:
                  projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
                  buildScriptName: build-sb-chroma
                  traceChanged: true
                  onlyChanged: true # TurboSnap
                  exitOnceUploaded: true # The PRs will be marked as success/failure based on the Chromatic build status


