# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: CI

on:
    push:
        branches: ["master"]
    pull_request:
        branches: ["master"]

concurrency:
    group: ${{ github.ref }}
    cancel-in-progress: true

jobs:
    eslint:
        name: "Eslint"
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version-file: ".nvmrc"
            - name: Install Dependencies
              run: yarn install --frozen-lockfile
            - name: Lint Eslint
              run: yarn lint-ci-eslint

    stylelint:
        name: "Stylelint"
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version-file: ".nvmrc"
            - name: Install Dependencies
              run: yarn install --frozen-lockfile
            - name: Lint Stylelint
              run: yarn lint-ci-style

    build_and_tests:
        name: "Build and Tests"
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version-file: ".nvmrc"
            - name: Install Dependencies
              run: yarn install --frozen-lockfile
            - name: Build Packages
              run: yarn build
            - name: Run Jest
              run: yarn test
